name: Demo of Action Validate Image 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name : Run EC Validate (keyless)
      uses: enterprise-contract/action-validate-image@v1.0.1
      with:
        image: ghcr.io/enterprise-contract/golden-container:latest
        identity: https:\/\/github\.com\/(slsa-framework\/slsa-github-generator|enterprise-contract\/golden-container)\/
        issuer: https://token.actions.githubusercontent.com
